apiVersion: v1
kind: Pod
metadata:
  name: any-name-that-you-like
  labels:
    label-name-1: label-value
    another-label: my-app-name
spec:
  containers:
    - image: nginx:alpine
      name: nginx-container
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
